-- MySQL Script generated by MySQL Workbench
-- Fri Apr 20 20:26:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video` (
  `idvideo` INT NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idvideo`),
  UNIQUE INDEX `idvideo_UNIQUE` (`idvideo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `idcourse` INT NOT NULL,
  `courseName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcourse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `idquestion` INT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `message` LONGBLOB NOT NULL,
  `idcourse` INT NOT NULL,
  `iduser` INT NOT NULL,
  PRIMARY KEY (`idquestion`, `idcourse`, `iduser`),
  INDEX `idCourse_idx` (`idcourse` ASC),
  INDEX `iduser_idx` (`iduser` ASC),
  CONSTRAINT `idCourse`
    FOREIGN KEY (`idcourse`)
    REFERENCES `mydb`.`course` (`idcourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `iduser`
    FOREIGN KEY (`iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reponse` (
  `idreponse` INT NOT NULL,
  `iduser` INT NOT NULL,
  `message` LONGBLOB NULL,
  `idquestion` INT NOT NULL,
  `timestamp` DATETIME NULL,
  PRIMARY KEY (`idreponse`, `idquestion`, `iduser`),
  UNIQUE INDEX `idreponse_UNIQUE` (`idreponse` ASC),
  INDEX `iduser_idx` (`iduser` ASC),
  INDEX `idquestion_idx` (`idquestion` ASC),
  CONSTRAINT `iduser`
    FOREIGN KEY (`iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idquestion`
    FOREIGN KEY (`idquestion`)
    REFERENCES `mydb`.`question` (`idquestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`remark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`remark` (
  `idremark` INT NOT NULL,
  `idvideo` INT NOT NULL,
  `iduser` INT NOT NULL,
  `timestamp` DATETIME NULL,
  `message` LONGBLOB NULL,
  PRIMARY KEY (`idremark`, `idvideo`, `iduser`),
  INDEX `idvideo_idx` (`idvideo` ASC),
  CONSTRAINT `idvideo`
    FOREIGN KEY (`idvideo`)
    REFERENCES `mydb`.`video` (`idvideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `iduser`
    FOREIGN KEY ()
    REFERENCES `mydb`.`user` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`remarkupvote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`remarkupvote` (
  `idremarkupvote` INT NOT NULL,
  `iduser` INT NOT NULL,
  `idremark` INT NOT NULL,
  PRIMARY KEY (`idremarkupvote`, `iduser`, `idremark`),
  CONSTRAINT `idremark`
    FOREIGN KEY ()
    REFERENCES `mydb`.`remark` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `iduser`
    FOREIGN KEY ()
    REFERENCES `mydb`.`user` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`responseupvote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`responseupvote` (
  `idresponseupvote` INT NOT NULL,
  `iduser` INT NOT NULL,
  `idresponse` INT NOT NULL,
  PRIMARY KEY (`idresponseupvote`, `iduser`, `idresponse`),
  INDEX `iduser_idx` (`iduser` ASC),
  CONSTRAINT `iduser`
    FOREIGN KEY (`iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idresponse`
    FOREIGN KEY ()
    REFERENCES `mydb`.`reponse` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`questionupvote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questionupvote` (
  `idquestionupvote` INT NOT NULL,
  `iduser` INT NOT NULL,
  `idquestion` INT NOT NULL,
  PRIMARY KEY (`idquestionupvote`, `iduser`, `idquestion`),
  INDEX `idquestion_idx` (`idquestion` ASC),
  INDEX `iduser_idx` (`iduser` ASC),
  CONSTRAINT `iduser`
    FOREIGN KEY (`iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idquestion`
    FOREIGN KEY (`idquestion`)
    REFERENCES `mydb`.`question` (`idquestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`questionupvote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questionupvote` (
  `idquestionupvote` INT NOT NULL,
  `iduser` INT NOT NULL,
  `idquestion` INT NOT NULL,
  PRIMARY KEY (`idquestionupvote`, `iduser`, `idquestion`),
  INDEX `idquestion_idx` (`idquestion` ASC),
  INDEX `iduser_idx` (`iduser` ASC),
  CONSTRAINT `iduser`
    FOREIGN KEY (`iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idquestion`
    FOREIGN KEY (`idquestion`)
    REFERENCES `mydb`.`question` (`idquestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
